import { generateText, streamText } from 'ai'
import { getModel } from './openrouter'
import {
  getInterviewerSystemPrompt,
  getScoringSystemPrompt,
  getSummarySystemPrompt
} from './assessment-prompts'

export interface AssessmentContext {
  jobTitle: string
  companyName: string
  candidateName: string
  questions: Array<{
    id: string
    orderIndex: number
    questionText: string
    scoringRubric: string | null
  }>
  currentQuestionIndex: number
  chatHistory: Array<{ role: 'user' | 'assistant'; content: string }>
}

export interface ScoringResult {
  score: number
  rationale: string
}

export interface AssessmentSummary {
  summary: string
  strengths: string[]
  areasForImprovement: string[]
}

// Generate AI interviewer response (streaming)
export async function generateInterviewerResponse(context: AssessmentContext) {
  const systemPrompt = getInterviewerSystemPrompt({
    jobTitle: context.jobTitle,
    companyName: context.companyName,
    candidateName: context.candidateName,
    questions: context.questions,
    currentQuestionIndex: context.currentQuestionIndex,
  })

  const result = await streamText({
    model: getModel(),
    system: systemPrompt,
    messages: context.chatHistory,
  })

  return result
}

// Generate AI interviewer response (non-streaming, for simpler cases)
export async function generateInterviewerResponseSync(context: AssessmentContext): Promise<string> {
  const systemPrompt = getInterviewerSystemPrompt({
    jobTitle: context.jobTitle,
    companyName: context.companyName,
    candidateName: context.candidateName,
    questions: context.questions,
    currentQuestionIndex: context.currentQuestionIndex,
  })

  const result = await generateText({
    model: getModel(),
    system: systemPrompt,
    messages: context.chatHistory,
  })

  return result.text
}

// Score a candidate's response
export async function scoreResponse(
  question: string,
  response: string,
  scoringRubric: string | null
): Promise<ScoringResult> {
  const systemPrompt = getScoringSystemPrompt()

  const userPrompt = `QUESTION:
${question}

${scoringRubric ? `SCORING RUBRIC:
${scoringRubric}

` : ''}CANDIDATE'S RESPONSE:
${response}

Please score this response.`

  const result = await generateText({
    model: getModel(),
    system: systemPrompt,
    prompt: userPrompt,
  })

  try {
    // Extract JSON from the response
    const jsonMatch = result.text.match(/\{[\s\S]*\}/)
    if (jsonMatch) {
      const parsed = JSON.parse(jsonMatch[0])
      return {
        score: Math.min(100, Math.max(0, parsed.score)),
        rationale: parsed.rationale || 'Score generated by AI assessment',
      }
    }
  } catch (e) {
    console.error('Failed to parse scoring response:', e)
  }

  // Fallback if parsing fails
  return {
    score: 50,
    rationale: 'Unable to parse AI scoring response',
  }
}

// Generate assessment summary
export async function generateAssessmentSummary(
  questionResponses: Array<{
    question: string
    response: string
    score: number
  }>,
  candidateName: string,
  jobTitle: string
): Promise<AssessmentSummary> {
  const systemPrompt = getSummarySystemPrompt()

  const transcript = questionResponses
    .map((qr, i) => `Question ${i + 1}: ${qr.question}\nResponse: ${qr.response}\nScore: ${qr.score}/100`)
    .join('\n\n')

  const userPrompt = `CANDIDATE: ${candidateName}
POSITION: ${jobTitle}

ASSESSMENT TRANSCRIPT:
${transcript}

Please provide a summary of this candidate's performance.`

  const result = await generateText({
    model: getModel(),
    system: systemPrompt,
    prompt: userPrompt,
  })

  try {
    const jsonMatch = result.text.match(/\{[\s\S]*\}/)
    if (jsonMatch) {
      const parsed = JSON.parse(jsonMatch[0])
      return {
        summary: parsed.summary || 'Assessment completed.',
        strengths: Array.isArray(parsed.strengths) ? parsed.strengths : [],
        areasForImprovement: Array.isArray(parsed.areasForImprovement) ? parsed.areasForImprovement : [],
      }
    }
  } catch (e) {
    console.error('Failed to parse summary response:', e)
  }

  // Fallback
  return {
    summary: 'Assessment completed. Review individual question scores for details.',
    strengths: [],
    areasForImprovement: [],
  }
}
